services:
  - type: web
    name: litassist
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: OPENROUTER_KEY
        sync: false
